"""1.2.8

Revision ID: 7c14267ffbe4
Revises: a19a48dbb41b
Create Date: 2023-05-13 11:42:58.215215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c14267ffbe4'
down_revision = 'a19a48dbb41b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('UP_LIMIT', sa.Text, nullable=True))
            batch_op.add_column(sa.Column('DL_LIMIT', sa.Text, nullable=True))
    except Exception as e:
        pass


def downgrade() -> None:
    pass
