"""1.3.1

Revision ID: eb3437042cc8
Revises: ff1b04a637f8
Create Date: 2023-11-22 17:07:42.765426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3437042cc8'
down_revision = 'ff1b04a637f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('DOWNLOADER') as batch_op:
            batch_op.add_column(sa.Column('ONLY_NASTOOL', sa.Integer(), nullable=True))
    except Exception as e:
        pass
    try:
        with op.batch_alter_table('TORRENT_REMOVE_TASK') as batch_op:
            batch_op.add_column(sa.Column('ONLY_NASTOOL', sa.Integer(), nullable=True))
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
